version: '3.8'

services:
  mysql_auth:
    image: mysql:8.0
    container_name: Node_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_password
    ports:
      - "3307:3306" # Puerto externo 3307
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: